---
title: A02
author: ''
date: '2022-03-24'
slug: a01
categories: []
tags: []
---
```{r}
# excel file reading
library(readxl)
prof_props <- read_excel("C:\\Users\\amoam\\Downloads\\Professor_Proposes_Data.xlsx")
prof_props
```
## Installing packages for linear regression
```{r}
library(boot)
# install.packages('ISLR')
library(ggplot2)
library(ISLR)
library(dplyr)
```

```{r}
glimpse(prof_props)

```
### Prep
```{r}
set.seed(1)
train <- sample(440, 220)
head(train)
```

```{r}
attach(prof_props)
```

## Attempt to transform descriptive data into metric
```{r}
prof_props$Certification <- as.factor(Certification)
prof_props$Clarity <- as.factor(Clarity)
prof_props$Cut <- as.factor(Cut)
prof_props$Symmetry <- as.factor(Symmetry)
prof_props$Wholesaler <- as.factor(Wholesaler)
prof_props$Polish <- as.factor(Polish)
prof_props$Colour <- as.factor(Colour)
prof_props
```

# Frequency Distribution
### Certification
```{r}
count(prof_props, Certification)
```
```{r}
ggplot(prof_props, aes(x = Certification, fill = Certification)) +
  geom_histogram(binwidth = 20, stat = "count") +
  scale_fill_hue(c=45, l=80)
```
### Clarity
```{r}
count(prof_props, Clarity)
```
```{r}
ggplot(prof_props, aes(x = Clarity, fill = Clarity)) +
  geom_histogram(binwidth = 20, stat = "count")+
  scale_fill_hue(c=45, l=80)
```

### Cut
```{r}
count(prof_props, Cut)
```
```{r}
ggplot(prof_props, aes(x = Cut, fill = Cut)) +
  geom_histogram(binwidth = 20, stat = "count") +
  scale_fill_hue(c=45, l=80)
```

### Symmetry
```{r}
count(prof_props, Symmetry)
```
```{r}
ggplot(prof_props, aes(x = Symmetry, fill = Symmetry)) +
  geom_histogram(binwidth = 20, stat = "count") +
  scale_fill_hue(c=45, l=80)
```
### Wholesaler
>>> Won't have impact on quality of diamond  

```{r}
count(prof_props, Wholesaler)
```

```{r}
ggplot(prof_props, aes(x = Wholesaler, fill = Wholesaler)) +
  geom_histogram(binwidth = 20, stat = "count") +
  scale_fill_hue(c=45, l=80)
```

### Polish
```{r}
count(prof_props, Polish)
```
```{r}
ggplot(prof_props, aes(x = Polish, fill = Polish)) +
  geom_histogram(binwidth = 20, stat = "count") +
  scale_fill_hue(c=45, l=80)
```

### Colour
```{r}
count(prof_props, Colour)
```
```{r}
ggplot(prof_props, aes(x = Colour, fill = Colour)) +
  geom_histogram(binwidth = 20, stat = "count") +
  scale_fill_hue(c=45, l=80)
```


```{r}
# Clarity
fact <- factor(Clarity)
levels(fact)
fact_Clarity <- as.numeric(fact)
fact_Clarity
```

```{r}
# Symmetry
# relevel the factors to match the level of the variable
fact1 <- factor(Symmetry)
levels(fact1)
fact_Symm <- as.numeric(fact1)
fact_Symm
```

```{r}
# Certification
# need to combine the levels into a single factor since there isn't a "better" certification
fact2 <- factor(Certification)
levels(fact2)
levels(fact2) <- c(1, 1, 1 ,1, 1)
factor(fact2)
```

```{r}
# Polish
fact3 <- factor(Polish)
levels(fact3) # There are two Vs? I have to change factor of the second V and X to 4 and 5 rather than 5 and 6
levels(fact3) <- c(1, 2, 3 ,4, 4, 5)
fact3
```

```{r}
# Wholesaler
fact4 <- factor(Wholesaler)
fact_Wh <- as.numeric(fact4)
fact_Wh
```

## Linear Model fitting
```{r}
lm.fit <- lm(Price~Cut, data = prof_props, subset = train)
lm.fit
```
# Bootstrap 1
```{r}
boot_func <- function(data, index) {
  fit <- coef(lm(Price ~ Cut, data = data, subset = index))
}
```

```{r}
int <- boot_func(prof_props, 1:440)
int
```
```{r}
set.seed(1)
boot_func(prof_props, sample(440,440, replace = T))
```

```{r}
boot.out <- boot(prof_props, boot_func, 1001)
boot.out
plot(boot.out)
```
# Bootstrap 2
```{r}
boot.func <- function(data, index){
return(coef(lm(Price ~ fact_Symm, data=data,subset=index)))
}
boot.func(prof_props, 1:440)
set.seed(1)
boot.func(prof_props, sample(440, 440, replace=T))
boot.out2 <- boot(prof_props, boot.func, 1001)
```

```{r}
plot(boot.out2)
```

# Bootstrap 3
```{r}
boot_func <- function(data, index) {
  fit <- coef(lm(Price ~ Colour, data = data, subset = index))
}
int <- boot_func(prof_props, 1:440)
int
set.seed(1)
boot_func(prof_props, sample(440,440, replace = T))
boot.out3 <- boot(prof_props, boot_func, 1001)
boot.out3
```
```{r}
plot(boot.out3)
```
# Bootstrap 4
```{r}
boot_func <- function(data, index) {
  fit <- coef(lm(Price ~ Carat, data = data, subset = index))
}
int <- boot_func(prof_props, 1:440)
int
set.seed(1)
boot_func(prof_props, sample(440,440, replace = T))
boot.out4 <- boot(prof_props, boot_func, 1001)
boot.out4
```
```{r}
plot(boot.out4)
```

# Bootstrap 5
```{r}
boot_func <- function(data, index) {
  fit <- coef(lm(Price ~ fact_Clarity, data = data, subset = index))
}
set.seed(1)
boot_func(prof_props, sample(440,440, replace = T))
boot.out5 <- boot(prof_props, boot_func, 1001)
boot.out5
```

```{r}
plot(boot.out5)
```

# Bootstrap 6
```{r}
boot_func <- function(data, index) {
  fit <- coef(lm(Price ~ fact_Cert, data = data, subset = index))
}
int <- boot_func(prof_props, 1:440)
int
set.seed(1)
boot_func(prof_props, sample(440,440, replace = T))
boot.out6 <- boot(prof_props, boot_func, 1001)
boot.out6
```
```{r}
plot(boot.out6)
```

# Bootstrp 7
```{r}
boot_func <- function(data, index) {
  fit <- coef(lm(Price ~ fact_Pol, data = data, subset = index))
}
int <- boot_func(prof_props, 1:440)
int
set.seed(1)
boot_func(prof_props, sample(440,440, replace = T))
boot.out7 <- boot(prof_props, boot_func, 1001)
boot.out7
```
```{r}
plot(boot.out7)
```
# Bootstrap 8
```{r}
boot_func <- function(data, index) {
  fit <- coef(lm(Price ~ fact_Wh, data = data, subset = index))
}
int <- boot_func(prof_props, 1:440)
int
set.seed(1)
boot_func(prof_props, sample(440,440, replace = T))
boot.out8 <- boot(prof_props, boot_func, 1001)
boot.out8
```
```{r}
plot(boot.out8)
```

